### ISSUE TITLE
Error message doesn't shows some text for Save/Restore commands

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/Cisco-NXOS-Switch-Shell-2G#7]
If restore nonexistent config-file by Restore command error message will raise.
But part of error message text shows as  ******* .
![image](https://user-images.githubusercontent.com/59359491/77045722-74ac9880-69ca-11ea-9d96-c582b047da38.png)

Log file for this event:

<pre>2020-03-19 08:08:06,828 [INFO]: QS.NSOX_for_test.Thread-21 driver - restore              Restore started
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session  Traceback (most recent call last):
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session    File "C:\ProgramData\QualiSystems\venv\Cisco_NXOS_Switch_2G_1_11\lib\site-packages\cloudshell\cli\session\ssh_session.py", line 63, in _initialize_session
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session      banner_timeout=30, allow_agent=False, look_for_keys=False, pkey=self.pkey)
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session    File "C:\ProgramData\QualiSystems\venv\Cisco_NXOS_Switch_2G_1_11\lib\site-packages\paramiko\client.py", line 385, in connect
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session      t.start_client(timeout=timeout)
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session    File "C:\ProgramData\QualiSystems\venv\Cisco_NXOS_Switch_2G_1_11\lib\site-packages\paramiko\transport.py", line 543, in start_client
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session      raise e
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session  SSHException: Error reading SSH protocol banner'utf8' codec can't decode byte 0xff in position 0: invalid start byte
2020-03-19 08:08:06,967 [ERROR]: QS.NSOX_for_test.Thread-21 ssh_session - _initialize_session  
2020-03-19 08:08:40,573 [ERROR]: QS.NSOX_for_test.Thread-21 system_actions - copy                 Copy Command failed. </pre>

**Comment by Costya-Y** [comment]
Hi @turkovda 

Can you please attach logs in debug mode?

Thank you,
Costya

**Comment by turkovda** [comment]
Attached
[NSOX_for_test--19-Mar-2020--09-05-39.log](https://github.com/QualiSystems/Cisco-NXOS-Switch-Shell-2G/files/4353593/NSOX_for_test--19-Mar-2020--09-05-39.log)
